FROM alpine

MAINTAINER Martin Saidl, martin.saidl@tone.cz

#Default firewall settings
ENV DATA_DIR=/config
ENV CHAIN=TWAMP
ENV IP=172.20.0.2

RUN apk add --no-cache iptables bash

COPY scripts/firewall.sh /sbin/firewall.sh
RUN chmod +x /sbin/firewall.sh

VOLUME ["${DATA_DIR}"]

ENTRYPOINT ["/sbin/firewall.sh"]
